### ISSUE TITLE
Add separate expiry to completed jobs

### ISSUE THREAD

**Issue by ghaydarov** [inkstak/activejob-status#19]
Currently, it seems that we have `expires_in` which apply to all jobs no matter that are complete or not.  If a job is complete, in most cases they maybe needed for shorted time than jobs that are in progress, scheduled, failed etc.

What do you think of an option like: `completed_job_expires_in` in config so that we can set it separately for completed jobs and remove them in a diff timeframe from the queue if completed.?

We could probably default it and make it optional.

**Comment by ghaydarov** [comment]
Something like this:

``` ruby 

    DEFAULT_OPTIONS = {
      expires_in: 60 * 30,
      expires_completed_jobs_in: 60 * 5,
      throttle_interval: 0
    }.freeze

      def update(job, message, force: false)
        @throttle.wrap(force: force) do
          message = read(job).merge(message)
          store.write(key(job), message, expires_in: expires_in(job))
        end
      end

      def expires_in(job)
        if job.status[:status] == :completed
          return @expires_completed_jobs_in
        else
          return @expires_in
        end
      end

```

**Comment by inkstak** [comment]
I would tend to think that it does not matter because this relies on caching mechanisms.

Let's imagine you use a long TTL : 

```ruby
ActiveJob::Status.options = { expires_in: 1.month.to_i }
```

When your job is complete, the status is updated one last time and it should live for 30 days.. unless your cache store needs to free space.

* Redis and MemCache support for automatic eviction when it reaches max memory
* Redis doesn't expire keys by default, it relies on eviction policy (least-frequently-used, least-recently-used, ...)
* MemoryStore & FileStore have a max-memory configuration but I don't know what eviction strategy it uses.

Memory should not be an issue for long TTL cached data.

**Comment by ghaydarov** [comment]
These are good points @inkstak, and educational too.  Thank you for the feedback. I am closing this issue.
