### ISSUE TITLE
Search by Job name

### ISSUE THREAD

**Issue by ghaydarov** [inkstak/activejob-status#28]
I have a use case for a job to be searchable by the name of a job. Say `MyAwesomeJob`. 

By that, I want to remove a job from the queue or act on it somehow.

One thought came to my mind is to restructure how we store that data in redis, maybe add it to the key or even make a nested structure to include job name too.

Other one is maybe search by the value and somehow scan for job name, not sure if it's possible with redis.

@inkstak any suggestion on this, how I can accomplish this? 

Thanks

**Comment by inkstak** [comment]
I'm not sure to understand what you want to achieve.

ActiveJob::Status cannot manipulate jobs, remove them or act on jobs. I don't think Activejob can even do that.
It would depends and rely on your background adapter (Sidekiq, DelayedJob, etc..)

For example, to search for a job in Sidekiq, you have to use the Sidekiq API: `Sidekiq::Queue`, `Sidekiq::ScheduleSet`, `Sidekiq::DeadSet`, etc..

Here is an example how to find and delete enqueued jobs matching a class name:

```ruby
Sidekiq::Queue.all.any? do |queue|
  queue.each do |job|
    job.delete if job.display_class == "MyAwesomeJob"
  end
end
```

However I don't think this is the right way: browsing jobs this way could very long when you have thousands of jobs and impact Sidekiq performances due to Redis locks.

If you need a job to be interrupted because of outside conditions, you can do that from the inside :
```ruby
class MyAwesomeJob < ApplicationJob
  def perform
    loop_something do
      return if status[:is_discarded]
    end
  end
end

jid = MyAwesomeJob.perform_later.id

# save its jid somewhere
# then later : 
status = ActiveJob::Status.get(jid)
status[:discarded] = true
```

**Comment by ghaydarov** [comment]
That's very good point. Seems like the best way to do it is to take care of it from inside the job. Thank you @inkstak
