### ISSUE TITLE
Jobs killed by Heroku have no indication of failure

### ISSUE THREAD

**Issue by jonasrcastanheira** [inkstak/activejob-status#38]
I'm running ActiveJob and ActiveJob::Status on a project with several simultaneous jobs hosted in Heroku. Sometimes, given the scale of some jobs and their memory requirements, Heroku kills some of those jobs (it's mainly due to lack of memory). ActiveJob::Status, however, keeps showing the status and progress of the job as if it were still running. Is there a way to track these killed jobs?

**Comment by inkstak** [comment]
Unfortunately no.
ActiveJob::Status relies on [ActiveJob callbacks](https://guides.rubyonrails.org/active_job_basics.html#available-callbacks).

When you say "Heroku kills some of those jobs" I guess it kills the process running the job and neither ActiveJob or ActiveJob::Status is warned about that: signals must be handled by your job backend (Sidekiq, Goodjob, SolidQueue...).

**Comment by inkstak** [comment]
Depending on you job backend & how Heroku is killing processes, you could catch some events:
For example: https://github.com/sidekiq/sidekiq/wiki/Deployment#events)

Otherwise you may need to implement a watchdog or check all statuses when booting a new process : take a look at #35 to list all statuses (which is also depends on your cache store backend).
